version: "3.7"
services:
  wallabag:
    image: wallabag/wallabag
    init: true
    container_name: wallabag
    environment:
      - SYMFONY__ENV__DOMAIN_NAME="https://${FQDN}"
      - SYMFONY__ENV__SERVER_NAME="${NAME}"
    volumes:
      - ./images:/var/www/wallabag/web/assets/images
      - ./data:/var/www/wallabag/data
