version: "3.7"
services:
  wallabag:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.wallabag.entrypoints=web
      - traefik.http.routers.wallabag.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.wallabag-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.wallabag.middlewares=wallabag-https-redirect
      - traefik.http.routers.wallabag-secure.entrypoints=websecure
      - traefik.http.routers.wallabag-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.wallabag-secure.tls=true
      - traefik.http.routers.wallabag-secure.tls.certresolver=letsencrypt

networks:
  proxy:
    external: true
