version: "3"

services:
  focalboard:
    image: mattermost/focalboard
    container_name: focalboard
    depends_on:
      - focalboard-db
    environment:
      VIRTUAL_HOST: $VIRTUAL_HOST
      VIRTUAL_PORT: $VIRTUAL_PORT
      VIRTUAL_PROTO: $VIRTUAL_PROTO
    volumes:
      - ./config.json:/opt/focalboard/config.json
    restart: always
    networks:
      - internal

  focalboard-db:
    image: postgres:latest
    container_name: focalboard-postgres
    restart: always
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    networks:
      - internal

networks:
  internal:

