version: "3"

services:
  focalboard:
    image: mattermost/focalboard
    container_name: focalboard
    depends_on:
      - focalboarddb
    env_file:
      - .env
    volumes:
      - ./config.json:/opt/focalboard/config.json
      - ./files:/opt/focalboard/files
    restart: always
    networks:
      - internal

  focalboarddb:
    image: postgres:latest
    container_name: focalboarddb
    restart: always
    volumes:
      - "./data:/var/lib/postgresql/data"
    env_file:
      - .env
    networks:
      - internal

networks:
  internal:

