version: '3.7'

services:
  logseq:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.logseq.loadbalancer.server.port=80
      - traefik.http.routers.logseq.entrypoints=http
      - traefik.http.routers.logseq.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.logseq-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.logseq.middlewares=logseq-https-redirect
      - traefik.http.routers.logseq-secure.entrypoints=https
      - traefik.http.routers.logseq-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.logseq-secure.tls=true
      - traefik.http.routers.logseq-secure.tls.certresolver=letsencrypt

networks:
  proxy:
    external: true

