version: '3'

services:
  zincobserve:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.zincobserve.loadbalancer.server.port=5080
      - traefik.http.routers.zincobserve.entrypoints=web
      - traefik.http.routers.zincobserve.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.zincobserver-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.zincobserve.middlewares=zinc-https-redirect
      - traefik.http.routers.zincobserve-secure.entrypoints=https
      - traefik.http.routers.zincobserve-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.zincobserve-secure.tls=true
      - traefik.http.routers.zincobserve-secure.tls.certresolver=letsencrypt

networks:
  proxy:
    external: true

