version: "3.7"

services:
  miniflux:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.miniflux.entrypoints=web
      - traefik.http.services.miniflux.loadbalancer.server.port=8080
      - traefik.http.routers.miniflux.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.miniflux-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.miniflux.middlewares=miniflux-https-redirect
      - traefik.http.routers.miniflux-secure.entrypoints=websecure
      - traefik.http.routers.miniflux-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.miniflux-secure.tls=true
      - traefik.http.routers.miniflux-secure.tls.certresolver=letsencrypt

networks:
  proxy:
    external: true
