version: "3"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - ./data:/data
    restart: always
    environment:
      - ADMIN_TOKEN=some_random_token_as_per_above_explanation
