version: "3"
services:
  postgres:
    image: postgres:10
    restart: unless-stopped
    networks:
      - invidious
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER $$POSTGRES_DB"]
  invidious:
    image: sriegler/invidious-auth:latest
    restart: unless-stopped
    networks:
      - invidious
    mem_limit: 1024M
    cpus: 0.5
    environment:
      INVIDIOUS_CONFIG: |
        channel_threads: 1
        check_tables: true
        feed_threads: 1
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: postgres
          port: 5432
        full_refresh: false
        https_only: false
        popular_enabled: false
        statistics_enabled: false
        domain: invidious.example.com
        external_port: 443
        registration_enabled: false
        captcha_enabled: false
        admins: []
        disable_proxy: false
        geo_bypass: false
    depends_on:
      - postgres

networks:
  invidious:
