version: "3"

services:
  invidious:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.invidious.loadbalancer.server.port=3000
      - traefik.http.routers.invidious.entrypoints=web
      - traefik.http.routers.invidious.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.invidious-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.invidious.middlewares=invidious-https-redirect
      - traefik.http.routers.invidious-secure.entrypoints=websecure
      - traefik.http.routers.invidious-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.invidious-secure.tls=true
      - traefik.http.routers.invidious-secure.tls.certresolver=letsencrypt

networks:
  proxy:
    external: true
