version: "3.7"

services:
  sftpgo:
    image: drakkan/sftpgo:alpine
    container_name: sftpgo
    init: true
    restart: unless-stopped
    ports:
      - 2022:2022
      - 10080:10080
    environment:
      - SFTPGO_WEBDAV__BINDINGS__0__PORT=10080
    volumes:
      - data:/sfv/sftpgo
      - home:/var/lib/sftpgo
    networks:
      - proxy

volumes:
  data: {}
  home: {}
networks:
  proxy:
    external: true
