version: "3"

services:
  trilium:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.trilium.loadbalancer.server.port=8080
      - traefik.http.routers.trilium.entrypoints=web
      - traefik.http.routers.trilium.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.trilium-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.trilium.middlewares=trilium-https-redirect
      - traefik.http.routers.trilium-secure.entrypoints=websecure
      - traefik.http.routers.trilium-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.trilium-secure.tls=true
      - traefik.http.routers.trilium-secure.tls.certresolver=letsencrypt

networks:
  proxy:
    external: true
