version: "3"

services:
  facturascripts:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.facturascripts.loadbalancer.server.port=80
      - traefik.http.routers.facturascripts.entrypoints=web
      - traefik.http.routers.facturascripts.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.facturascripts-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.facturascripts.middlewares=facturascripts-https-redirect
      - traefik.http.routers.facturascripts-secure.entrypoints=websecure
      - traefik.http.routers.facturascripts-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.facturascripts-secure.tls=true
      - traefik.http.routers.facturascripts-secure.tls.certresolver=letsencrypt

networks:
  proxy:
    external: true
