version: "3"

services:
  yacht:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.yacht.loadbalancer.server.port=3000
      - traefik.http.routers.yacht.entrypoints=web
      - traefik.http.routers.yacht.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.yacht-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.yacht.middlewares=yacht-https-redirect
      - traefik.http.routers.yacht-secure.entrypoints=websecure
      - traefik.http.routers.yacht-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.yacht-secure.tls=true
      - traefik.http.routers.yacht-secure.tls.certresolver=letsencrypt

networks:
  proxy:
    external: true
