version: "3.7"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    init: true
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - config:/config
      - cache:/cache
      - media:/media
    networks:
      - proxy
    labels:
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - traefik.http.routers.jellyfin.rule=Host(`${FQDN}`)

networks:
  proxy:
    external: true

volumes:
  config: {}
  cache: {}
  media: {}
