version: "3.7"

services:
  jellystat-db:
    image: postgres:15.2
    container_name: jellystat-db
    init: true
    environment:
      POSTGRES_DB: "jfstat"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data # Mounting the volume
  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    init: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: "my-secret-jwt-key"
    volumes:
      - backup-data:/app/backend/backup-data # Mounting the volume
    labels:
      - traefik.http.services.jellystat.loadbalancer.server.port=3000
      - traefik.http.routers.jellystat.rule=Host(`${FQDN}`)
    depends_on:
      - jellystat-db

networks:
  proxy:
    external: true

volumes:
  backup-data: {}
  postgres-data: {}
