version: "3.7"

services:
  memos:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.memos.loadbalancer.server.port=5230
      - traefik.http.routers.memos.entrypoints=web
      - traefik.http.routers.memos.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.memos-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.memos.middlewares=memos-https-redirect
      - traefik.http.routers.memos-secure.entrypoints=websecure
      - traefik.http.routers.memos-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.memos-secure.tls=true
      - traefik.http.routers.memos-secure.tls.certresolver=letsencrypt

networks:
  proxy:
    external: true
