version: "3.7"

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_for_wikijs
    init: true
    logging:
      driver: "none"
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - DB_TYPE
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASS
      - DB_NAME
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - internal

  wikijs:
    image: ghcr.io/requarks/wiki:2
    container_name: wikijs
    init: true
    depends_on:
      - db
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - DB_TYPE
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASS
      - DB_NAME
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
  proxy:
    external: true
