version: "3.7"

services:
  metube:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.metube.loadbalancer.server.port=8081
      - traefik.http.routers.metube.entrypoints=web
      - traefik.http.routers.metube.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.metube-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.metube.middlewares=metube-https-redirect
      - traefik.http.routers.metube-secure.entrypoints=websecure
      - traefik.http.routers.metube-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.metube-secure.tls=true
      - traefik.http.routers.metube-secure.tls.certresolver=letsencrypt

networks:
  proxy:
    external: true
