version: "3.7"

services:
  myadmin:
    image: phpmyadmin
    restart: always
    networks:
      - proxy
      - wp
    labels:
      - caddy="${FQDN}"
      - caddy.reverse_proxy="{{upstreams 80}}"
    environment:
      - PMA_ARBITRARY=1

networks:
  proxy:
    external: true
  wp:
    external: true
